version: '3.8'

services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "consumer_app.main:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true
    name: shared_kafka_network