services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    image: noctrunal/event-producer:latest
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
